spring:
  thymeleaf:
    cache: false
  profiles:
    active: production
  datasource:
    walnut-admin:
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 1000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800

server:
  tomcat:
    access_log_enabled: true
    basedir: target/tomcat

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
