server:
  port: 8081

spring:
  datasource:
    springboot:
      template:
        url: jdbc:mysql://127.0.0.1:3306/spbtemplate?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root